### ISSUE TITLE
No noticeable difference between animations

### ISSUE THREAD

**Issue by ddnexus** [amezin/gnome-shell-extension-ddterm#125] opened 2022-05-03 03:32 UTC
Minor issue & poaaible feature request.

Unless I use something like "impatience" to delay the nice animations, I don't notice any difference between different settings.

Setting impatience to 2 seconds, makes a difference, in  the "show" animation, but none in the "hide" one. The problem is that with 2 seconds delay, the rest of the system UI is slow as slow as a sloth! :)

Is there any way to change the timing of the animations, better independently?

**Comment by Batwam** [comment] 2022-05-08 14:19
which system are you using? I am noticing similar on Ubuntu 22.04 where opening/closing is pretty much instantaneous so really no difference between the various options. On Debian Unstable however, it's much slower and seems to work as intended.

**Comment by ddnexus** [comment] 2022-05-08 16:30
Yup, Ubuntu 22.04.
Since there are so many different platforms, I think the best would be adding some config to adjust the timing for different platforms and different personal preference.

**Closed** 2022-05-15 17:59 UTC

**Comment by ddnexus** [comment] 2022-05-17 03:20
Thank you!
