### ISSUE TITLE
Crashes during dnf upgrade

### ISSUE THREAD

**Issue by rrrzahar** [amezin/gnome-shell-extension-ddterm#99] opened 2021-11-06 16:34 UTC
Hello,
I recently installed your extension and it works very well but I noticed one issue. When I upgrade Fedora 35 (Wayland) then it disappear in the middle of that process. When I hit F12 then it starts a new session but dnf continues its work in background mode. Such happened some times.

**Comment by amezin** [comment] 2021-11-08 13:00
Yep, I've seen this issue once myself.
It seems to happen on Fedora only - not on Arch or Ubuntu/Debian.
Does it happen on every update for you? Because, as I said, I've seen it only once. I guess it's related to post-install scripts of some specific package

**Comment by rrrzahar** [comment] 2021-11-08 20:49
It doesn't happen every update. I saw it a couple times during last week. Does your extension have a debug mode? May be it can happens due to gjs update but I am not sure. I need more time to make sure in it.

**Comment by amezin** [comment] 2021-11-10 18:38
No, there is no special debug mode.

Just look at `journalctl -r` if it happens again.

Would also be interesting to see if GNOME Terminal experiences the same issue

**Comment by rrrzahar** [comment] 2021-11-10 22:14
No, Gnome terminal works very well. Never saw such issue! I am waiting it again

**Comment by amezin** [comment] 2021-11-15 20:45
I've been able to reproduce the issue by upgrading F35 Beta 1.1 VM.

However, in the logs, I got:
`ddterm app exited with status 0`

After adding debug printerrs all over the place, I figured out that something tries to disable the extension (i. e., the shell calls extension's "disable" function).

And somehow, upgrading systems triggers this issue. Maybe it's restarting user d-bus or something like that (although restarting user d-bus would kill almost all other applications, so it must be something different).

**Comment by rrrzahar** [comment] 2021-11-16 15:33
Yes, **dnf reinstall systemd-libs** really closes your extension but Gnome Terminal works very well and it doesn't close after reinstall systemd-libs. I have checked it a few times.

**Comment by amezin** [comment] 2021-11-17 01:21
Yes, GNOME Terminal is not affected, because it is not a shell extension.

Reinstalling systemd-libs triggers lots of GSettings notifications:

```
[amezin@fedora ~]$ gsettings monitor org.gnome.shell
always-show-log-out: false
command-history: @as []
disable-user-extensions: false
favorite-apps: ['firefox.desktop', 'org.gnome.Calendar.desktop', 'org.gnome.Music.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Software.desktop']
disable-extension-version-validation: false
app-picker-layout: [{'org.gnome.Contacts.desktop': <{'position': <0>}>, 'org.gnome.Weather.desktop': <{'position': <1>}>, 'org.gnome.clocks.desktop': <{'position': <2>}>, 'org.gnome.Maps.desktop': <{'position': <3>}>, 'org.gnome.Photos.desktop': <{'position': <4>}>, 'org.gnome.Totem.desktop': <{'position': <5>}>, 'org.gnome.Extensions.desktop': <{'position': <6>}>, 'org.gnome.Calculator.desktop': <{'position': <7>}>, 'org.gnome.gedit.desktop': <{'position': <8>}>, 'simple-scan.desktop': <{'position': <9>}>, 'gnome-control-center.desktop': <{'position': <10>}>, 'org.fedoraproject.MediaWriter.desktop': <{'position': <11>}>, 'gnome-system-monitor.desktop': <{'position': <12>}>, 'org.gnome.Boxes.desktop': <{'position': <13>}>, 'org.gnome.Terminal.desktop': <{'position': <14>}>, 'Utilities': <{'position': <15>}>, 'libreoffice-calc.desktop': <{'position': <16>}>, 'yelp.desktop': <{'position': <17>}>, 'libreoffice-impress.desktop': <{'position': <18>}>, 'org.gnome.Cheese.desktop': <{'position': <19>}>, 'libreoffice-writer.desktop': <{'position': <20>}>, 'rhythmbox.desktop': <{'position': <21>}>, 'org.gnome.Tour.desktop': <{'position': <22>}>, 'ca.desrt.dconf-editor.desktop': <{'position': <23>}>}]
had-bluetooth-devices-setup: false
looking-glass-history: @as []
enabled-extensions: ['background-logo@fedorahosted.org', 'ddterm@amezin.github.com']
disabled-extensions: @as []
development-tools: true
remember-mount-password: false
welcome-dialog-last-shown-version: '41.rc.1'
always-show-log-out: false
command-history: @as []
disable-user-extensions: false
favorite-apps: ['firefox.desktop', 'org.gnome.Calendar.desktop', 'org.gnome.Music.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Software.desktop']
disable-extension-version-validation: false
app-picker-layout: [{'org.gnome.Contacts.desktop': <{'position': <0>}>, 'org.gnome.Weather.desktop': <{'position': <1>}>, 'org.gnome.clocks.desktop': <{'position': <2>}>, 'org.gnome.Maps.desktop': <{'position': <3>}>, 'org.gnome.Photos.desktop': <{'position': <4>}>, 'org.gnome.Totem.desktop': <{'position': <5>}>, 'org.gnome.Extensions.desktop': <{'position': <6>}>, 'org.gnome.Calculator.desktop': <{'position': <7>}>, 'org.gnome.gedit.desktop': <{'position': <8>}>, 'simple-scan.desktop': <{'position': <9>}>, 'gnome-control-center.desktop': <{'position': <10>}>, 'org.fedoraproject.MediaWriter.desktop': <{'position': <11>}>, 'gnome-system-monitor.desktop': <{'position': <12>}>, 'org.gnome.Boxes.desktop': <{'position': <13>}>, 'org.gnome.Terminal.desktop': <{'position': <14>}>, 'Utilities': <{'position': <15>}>, 'libreoffice-calc.desktop': <{'position': <16>}>, 'yelp.desktop': <{'position': <17>}>, 'libreoffice-impress.desktop': <{'position': <18>}>, 'org.gnome.Cheese.desktop': <{'position': <19>}>, 'libreoffice-writer.desktop': <{'position': <20>}>, 'rhythmbox.desktop': <{'position': <21>}>, 'org.gnome.Tour.desktop': <{'position': <22>}>, 'ca.desrt.dconf-editor.desktop': <{'position': <23>}>}]
had-bluetooth-devices-setup: false
looking-glass-history: @as []
enabled-extensions: ['background-logo@fedorahosted.org', 'ddterm@amezin.github.com']
disabled-extensions: @as []
development-tools: true
remember-mount-password: false
welcome-dialog-last-shown-version: '41.rc.1'
always-show-log-out: false
command-history: @as []
disable-user-extensions: false
favorite-apps: ['firefox.desktop', 'org.gnome.Calendar.desktop', 'org.gnome.Music.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Software.desktop']
disable-extension-version-validation: false
app-picker-layout: [{'org.gnome.Contacts.desktop': <{'position': <0>}>, 'org.gnome.Weather.desktop': <{'position': <1>}>, 'org.gnome.clocks.desktop': <{'position': <2>}>, 'org.gnome.Maps.desktop': <{'position': <3>}>, 'org.gnome.Photos.desktop': <{'position': <4>}>, 'org.gnome.Totem.desktop': <{'position': <5>}>, 'org.gnome.Extensions.desktop': <{'position': <6>}>, 'org.gnome.Calculator.desktop': <{'position': <7>}>, 'org.gnome.gedit.desktop': <{'position': <8>}>, 'simple-scan.desktop': <{'position': <9>}>, 'gnome-control-center.desktop': <{'position': <10>}>, 'org.fedoraproject.MediaWriter.desktop': <{'position': <11>}>, 'gnome-system-monitor.desktop': <{'position': <12>}>, 'org.gnome.Boxes.desktop': <{'position': <13>}>, 'org.gnome.Terminal.desktop': <{'position': <14>}>, 'Utilities': <{'position': <15>}>, 'libreoffice-calc.desktop': <{'position': <16>}>, 'yelp.desktop': <{'position': <17>}>, 'libreoffice-impress.desktop': <{'position': <18>}>, 'org.gnome.Cheese.desktop': <{'position': <19>}>, 'libreoffice-writer.desktop': <{'position': <20>}>, 'rhythmbox.desktop': <{'position': <21>}>, 'org.gnome.Tour.desktop': <{'position': <22>}>, 'ca.desrt.dconf-editor.desktop': <{'position': <23>}>}]
had-bluetooth-devices-setup: false
looking-glass-history: @as []
enabled-extensions: ['background-logo@fedorahosted.org', 'ddterm@amezin.github.com']
disabled-extensions: @as []
development-tools: true
remember-mount-password: false
welcome-dialog-last-shown-version: '41.rc.1'
```

I've added `logError(new Error('ddterm is being disabled!'))` line into `disable()`:

```
ноя 17 07:05:04 fedora sudo[28986]:   amezin : TTY=pts/0 ; PWD=/home/amezin ; USER=root ; COMMAND=/usr/bin/dnf reinstall systemd-libs
ноя 17 07:05:04 fedora audit[28986]: CRED_REFR pid=28986 uid=1000 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_localuser,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
ноя 17 07:05:04 fedora sudo[28986]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
ноя 17 07:05:04 fedora audit[28986]: USER_START pid=28986 uid=1000 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
ноя 17 07:05:09 fedora gsd-usb-protect[27884]: Failed to fetch USBGuard rules list: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
ноя 17 07:05:09 fedora gsd-usb-protect[27884]: Failed to fetch USBGuard rules list: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
ноя 17 07:05:09 fedora gsd-usb-protect[27884]: Failed to fetch USBGuard rules list: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
ноя 17 07:05:09 fedora gsd-usb-protect[27884]: Failed to fetch USBGuard rules list: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
ноя 17 07:05:09 fedora gsd-usb-protect[27884]: Failed to fetch USBGuard rules list: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
ноя 17 07:05:09 fedora gsd-usb-protect[27884]: Failed to fetch USBGuard rules list: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
ноя 17 07:05:09 fedora gnome-shell[27612]: JS ERROR: Error: ddterm is being disabled!
                                              disable@/home/amezin/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/extension.js:207:18
                                              _callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:107:32
                                              _onVersionValidationChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:517:18
                                              _onVersionValidationChanged@resource:///org/gnome/shell/ui/extensionSystem.js:516:42
ноя 17 07:05:09 fedora systemd[1]: Starting Location Lookup Service...
ноя 17 07:05:09 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=geoclue comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
ноя 17 07:05:09 fedora systemd[1]: Started Location Lookup Service.
ноя 17 07:05:09 fedora gnome-shell[27612]: JS ERROR: Error: ddterm is being disabled!
                                              disable@/home/amezin/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/extension.js:207:18
                                              _callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:107:32
                                              _onVersionValidationChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:517:18
                                              _onVersionValidationChanged@resource:///org/gnome/shell/ui/extensionSystem.js:516:42
ноя 17 07:05:09 fedora systemd[1]: Started /usr/bin/systemctl start man-db-cache-update.
ноя 17 07:05:09 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=run-r8870ed8a766c49ae925daa3ed3195e17 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
ноя 17 07:05:09 fedora systemd[1]: Starting man-db-cache-update.service...
ноя 17 07:05:09 fedora systemd[1]: Started /usr/bin/systemctl start man-db-cache-update.
ноя 17 07:05:09 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=run-rdb36769dfb8849a892bcf938cd75056c comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
ноя 17 07:05:09 fedora audit[28986]: USER_END pid=28986 uid=1000 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
ноя 17 07:05:09 fedora audit[28986]: CRED_DISP pid=28986 uid=1000 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_localuser,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
ноя 17 07:05:09 fedora sudo[28986]: pam_unix(sudo:session): session closed for user root
ноя 17 07:05:09 fedora systemd[1535]: vte-spawn-e3f813d3-c519-45f4-9f8e-8f6c75d1866e.scope: Consumed 2.031s CPU time.
ноя 17 07:05:09 fedora gnome-shell[27612]: JS ERROR: Error: ddterm is being disabled!
                                              disable@/home/amezin/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/extension.js:207:18
                                              _callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:107:32
                                              _onVersionValidationChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:517:18
                                              _onVersionValidationChanged@resource:///org/gnome/shell/ui/extensionSystem.js:516:42
ноя 17 07:05:09 fedora gnome-shell[27612]: ddterm app exited with status 0
```

So `disable()` is called from [`_onVersionValidationChanged()`](https://github.com/GNOME/gnome-shell/blob/351fbef55e258cd866e4e7281b08059d0e244ea7/js/ui/extensionSystem.js#L510-L524)... Which is apparently triggered by a "change" in `disable-extension-version-validation` setting https://github.com/GNOME/gnome-shell/blob/351fbef55e258cd866e4e7281b08059d0e244ea7/js/ui/extensionSystem.js#L556-L557

This can only be fixed in GNOME Shell itself (or in Fedora packaging).

If the extension is being disabled by the shell, the extension shouldn't keep the app running (unless there is some clear indicator, like in lock screen mode workaround)

**Comment by rrrzahar** [comment] 2021-11-17 13:19
I don't understand one thing! As you said before that Debian/Ubuntu doesn't have such issue. Do they use another version of GNOME shell?

**Comment by amezin** [comment] 2021-11-18 01:27
They have different post-install scripts for systemd package(s) that don't trigger these (fake) GSettings change notifications.

**Comment by rrrzahar** [comment] 2021-11-18 16:33
All right, thank you for your time!

**Comment by amezin** [comment] 2021-11-19 18:42
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4808

**Comment by amezin** [comment] 2021-11-19 20:00
`dconf watch` also shows spurious notifications:

```
[amezin@fedora ~]$ dconf watch /org/gnome/shell
/

/

/

```

And `dconf-service` isn't restarted:

```
[amezin@fedora ~]$ ps -A | grep dconf
  37338 ?        00:00:00 dconf-service
  37775 ?        00:00:00 ibus-dconf
[amezin@fedora ~]$ sudo dnf reinstall systemd-libs
...
[amezin@fedora ~]$ ps -A | grep dconf
  37338 ?        00:00:00 dconf-service
  37775 ?        00:00:00 ibus-dconf
```

Interesting

**Comment by rrrzahar** [comment] 2021-11-21 16:17
The most interesting thing that your extension works correctly when Fedora live CD is used. **dnf rei systemd-libs** doesn't disable it.

**Comment by Movisivi** [comment] 2021-12-05 02:24
What's the status of this getting fixed? I see a bunch of recent activity on the links above but I'm too dumb to understand them

**Comment by amezin** [comment] 2022-01-27 04:30
So https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2047 has finally been merged, and GNOME devs promised to include it in the next 40.* and 41.* stable releases. The rest is outside of my control.

**Closed by amezin** 2022-01-27 04:30 UTC
